### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ArtLion74** [two-pack/redmine_xlsx_format_issue_exporter#10]
Hi,

First off all - I'm the beginner in Redmine and Ruby :)

Environment : 
Ubuntu 14.04 Server Edition
ruby 1.9.3p484
gem 1.8.23
rails 3.2.2.1
java 1.8.0_31

I installed plugin as described (copy to plugin, bundle install, apache2 restart).

Link XSLX is working and after click give me new window with options : selected columns, all columns, description, files and two buttons Export and Cancel.

Adres in my browser is : 
http://brp.pkp-cargo.eu/projects/cargo-bi/issues

![image](https://cloud.githubusercontent.com/assets/10630374/6041900/cf255804-ac80-11e4-851c-be1c4bc4438f.png)

After Export I receive page 404:

Page not found
The page you were trying to access doesn't exist or has been removed.
Back

Adres in my browser is : 
http://brp.pkp-cargo.eu/projects/cargo-bi/xlsx_export?utf8=%E2%9C%93&columns=

![image](https://cloud.githubusercontent.com/assets/10630374/6041908/e74a1898-ac80-11e4-8e1c-382f48a07d06.png)

What's wrong ? What can I check to start using your plugin ?

Regards, Artur

**Comment by two-pack** [comment]
I couldn't reproduce it on Redmine 2.6.1 and the plugin 0.1.1.
Please check followings:
* What version do you use?
* What plugins do you use with this plugin if you use them?
* Please check Redmine log.

**Comment by ArtLion74** [comment]
Hi,

Below is picture of plugin I use.

![image](https://cloud.githubusercontent.com/assets/10630374/6059743/7a487e78-ad35-11e4-991c-63186ab9a4e4.png)

I have this in log file after debug state:

Completed 200 OK in 212.3ms (Views: 62.8ms | ActiveRecord: 106.0ms)
Started GET "/projects/cargo-bi/xlsx_export?utf8=%E2%9C%93&columns=all" for 10.90.26.15 at 2015-02-05 12:54:09 +0100

AbstractController::ActionNotFound (The action 'cargo-bi' could not be found for ProjectsController):
  actionpack (3.2.21) lib/abstract_controller/base.rb:116:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'

.... and much more errors.

What can I do ?

**Comment by ArtLion74** [comment]
OK, I found the problem :)
It's redcase plugin and routes.rb
They put into command:

match ':controller(/:action(/:id))(.:format)'

which make disaster.
I found replacement for that :

post ':controller(/:action(/:id(.:format)))'

It's working almost everywhere but definitely help yours plugin :)
Sorry for bothering you ;)
