### ISSUE TITLE
Export link does not appear

### ISSUE THREAD

**Issue by arnisjuraga** [two-pack/redmine_xlsx_format_issue_exporter#26]
Hi!

I have  Redmine 3.3.0. After installation and Redmine restart, I can see plugin in the list, but I don't see Export link:

~~~
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  add_link                       0.0.1
  easy_gantt                     2016-RC1.0
  periodictask                   3.1.1
  redmine_custom_css             0.1.4
  redmine_improved_searchbox2    0.0.3
  redmine_lightbox2              0.3.1
  redmine_tagging                0.1.5
  redmine_theme_changer          0.2.0
  redmine_xlsx_format_issue_exporter 0.1.3
~~~

![image](https://cloud.githubusercontent.com/assets/2185289/20966426/e66e8d5a-bc82-11e6-9e1f-35cb3ca999e7.png)

**Comment by two-pack** [comment]
Thank you reporting :)
But I cannot reproduce it yet.
Could you reproduce except any plugins?
I think probably some plugin change html of issues page. So could you try remove some plugins and check the reason of the problem?

**Comment by arnisjuraga** [comment]
Oh my ... 
Tried without other plugins - and found a problem.
The reason was more then silly... - I had `Custom css` plugin with custom CSS styles, including:
~~~css
p.other-formats {
    display: none;
}
~~~

And links were just hidden.
Fixed, have it, great plugin!!!
