### ISSUE TITLE
Export to xlsx with Formula in Column

### ISSUE THREAD

**Issue by mbalecr7** [two-pack/redmine_xlsx_format_issue_exporter#48]
Hello,
First thanks for the plugin, i'm just in reflexion about the idea of adding formula ( excel formula ). It is possible to add formula into custom field and then when i export all issues in xlsx that the xlsx file contain formula for each column ? 

If the response is yes,  how can i proceed thank you

**Comment by two-pack** [comment]
Thanks your idea, but it goes against the concept of this plugin.
The concept of this plugin is **XLSX version of the function to export csv**.
So I decided not to implement a lot of enhancement for it.
