### ISSUE TITLE
Error message: undefined method `prepend' for IssuesController:Class (NoMethodError)

### ISSUE THREAD

**Issue by Cyrilberthelot** [two-pack/redmine_xlsx_format_issue_exporter#49]
Hi,

I did an upgrade from redmine 3.2 to the last version : 3.4.2 but the plugin is not working now
So I tried an update to the lastest version.
I remove the old plugin version from plugins directory  and I did  :

$cd plugins
$ git clone https://github.com/two-pack/redmine_xlsx_format_issue_exporter.git redmine_xlsx_format_issue_exporter
$ cd ..
$ bundle install --without test

But I got  the following error when I'm going on Redmine web page :

Error message:
    undefined method `prepend' for IssuesController:Class (NoMethodError)
Exception class:
    PhusionPassenger::UnknownError
Application root:
    /var/www/redmine 

0 | /var/www/redmine-3.4.2/plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/issues_controller_patch.rb | 26 | in `block in '
1 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 446 | in `instance_exec'
2 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 446 | in `block in make_lambda'
3 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 192 | in `call'
4 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 192 | in `block in simple'
5 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 504 | in `call'
6 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 504 | in `block in call'
7 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 504 | in `each'
8 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 504 | in `call'
9 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 92 | in `__run_callbacks__'
10 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 778 | in `_run_prepare_callbacks'
11 | /var/lib/gems/1.9.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb | 81 | in `run_callbacks'
12 | /var/lib/gems/1.9.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb | 83 | in `prepare!'
13 | /var/lib/gems/1.9.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb | 55 | in `prepare!'
14 | /var/lib/gems/1.9.1/gems/railties-4.2.8/lib/rails/application/finisher.rb | 50 | in `block in '
15 | /var/lib/gems/1.9.1/gems/railties-4.2.8/lib/rails/initializable.rb | 30 | in `instance_exec'
16 | /var/lib/gems/1.9.1/gems/railties-4.2.8/lib/rails/initializable.rb | 30 | in `run'
17 | /var/lib/gems/1.9.1/gems/railties-4.2.8/lib/rails/initializable.rb | 55 | in `block in run_initializers'
18 | /usr/lib/ruby/1.9.1/tsort.rb | 150 | in `block in tsort_each'
19 | /usr/lib/ruby/1.9.1/tsort.rb | 183 | in `block (2 levels) in each_strongly_connected_component'
20 | /usr/lib/ruby/1.9.1/tsort.rb | 219 | in `each_strongly_connected_component_from'
21 | /usr/lib/ruby/1.9.1/tsort.rb | 182 | in `block in each_strongly_connected_component'
22 | /usr/lib/ruby/1.9.1/tsort.rb | 180 | in `each'
23 | /usr/lib/ruby/1.9.1/tsort.rb | 180 | in `each_strongly_connected_component'
24 | /usr/lib/ruby/1.9.1/tsort.rb | 148 | in `tsort_each'
25 | /var/lib/gems/1.9.1/gems/railties-4.2.8/lib/rails/initializable.rb | 54 | in `run_initializers'
26 | /var/lib/gems/1.9.1/gems/railties-4.2.8/lib/rails/application.rb | 352 | in `initialize!'
27 | /var/www/redmine-3.4.2/config/environment.rb | 14 | in `'
28 | config.ru | 3 | in `require'
29 | config.ru | 3 | in `block in '
30 | /var/lib/gems/1.9.1/gems/rack-1.6.8/lib/rack/builder.rb | 55 | in `instance_eval'
31 | /var/lib/gems/1.9.1/gems/rack-1.6.8/lib/rack/builder.rb | 55 | in `initialize'
32 | config.ru | 1 | in `new'
33 | config.ru | 1 | in `'
34 | /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb | 225 | in `eval'
35 | /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb | 225 | in `load_rack_app'
36 | /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb | 157 | in `block in initialize_server'
37 | /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb | 572 | in `report_app_init_status'
38 | /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb | 154 | in `initialize_server'
39 | /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb | 204 | in `start_synchronously'
40 | /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb | 180 | in `start'
41 | /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb | 129 | in `start'
42 | /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb | 253 | in `block (2 levels) in spawn_rack_application'
43 | /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb | 132 | in `lookup_or_add'
44 | /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb | 246 | in `block in spawn_rack_application'
45 | /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb | 82 | in `block in synchronize'
46 |   | prelude> | 10:in `synchronize'
47 | /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb | 79 | in `synchronize'
48 | /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb | 244 | in `spawn_rack_application'
49 | /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb | 137 | in `spawn_application'
50 | /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb | 275 | in `handle_spawn_application'
51 | /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb | 357 | in `server_main_loop'
52 | /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb | 206 | in `start_synchronously'
53 | /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server | 99 | in `'

Thanks for your help !
Regards,
Cyril.

**Comment by Cyrilberthelot** [comment]
Hi,

Thanks for your quick reply.
You are right i'm using Ruby 1.9.3.
For some bug issue we have to use Redmine 3.4.2.
I don't know if it's easy to upgrade to Ruby 2.0.0 on debian 7.
Normally after this update I will be able to use your plugin with 
Redmine 3.4.2 right ?

Regards,
Cyril.

**Comment by two-pack** [comment]
@Cyrilberthelot Yes. Unfortunately you have other problem, please tell me details on GitHub :)

**Comment by Cyrilberthelot** [comment]
Hi,

Which details do you need ? 

Regards,
Cyril.

**Comment by two-pack** [comment]
> Which details do you need ?

Do you have other problem after upgrading ruby to 2.x?
If you have it, please tell me your environment, error log, etc...

> Normally after this update I will be able to use your plugin with Redmine 3.4.2 right ?

I DID NOT test upgrade older version to 3.4.2.
But on 3.4.2, I passed the test and checked exporting xlsx issues list.
