### ISSUE TITLE
Export all issues instead of only one page.

### ISSUE THREAD

**Issue by mrscylla** [two-pack/redmine_xlsx_format_issue_exporter#52]
Plugin exports only one page of issues. Not more then 150.

**Comment by two-pack** [comment]
Thanks your idea, but it goes against the concept of this plugin.
The concept of this plugin is XLSX version of the function to export csv.
The function to export CSV restricts to a maximum of 500 issues.
So I decided not to implement a lot of enhancement for it.

If you export more than 150, Change setting of **Administration - Settings - General - Objects per page options** .
