### ISSUE TITLE
Maximum export issues parameter

### ISSUE THREAD

**Issue by mrscylla** [two-pack/redmine_xlsx_format_issue_exporter#53]
It would be nice to have possibility to change maximum issues count

**Comment by two-pack** [comment]
Thanks your idea, but it goes against the concept of this plugin.
The concept of this plugin is XLSX version of the function to export csv.
The function to export CSV restricts to a maximum of 500 issues by setting.yml.
So I decided not to implement a lot of enhancement for it.

If you want to export over 500, Change **issues_export_limit** in **$REDMINE_ROOT/config/setting.yml** .
