### ISSUE TITLE
Failed all tests with Capybara error log.

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xlsx_format_issue_exporter#54]
Failed all tests with Capybara error log on Travis-CI.
Error log is like following:
~~~
 1) Error:
RedmineXlsxFormatIssueExporter::IssuesIndexPageTest#test_that_export_with_selected_columns:
LoadError: Capybara is unable to load `puma` for its server, please add `puma` to your project or specify a different server via something like `Capybara.server = :webrick`.
~~~

Its caused after using Capybara 3.0.3.
* [Failed build](https://travis-ci.org/two-pack/redmine_xlsx_format_issue_exporter/builds/373556198)
* [Succeeded build](https://travis-ci.org/two-pack/redmine_xlsx_format_issue_exporter/builds/372732791)

**Comment by two-pack** [comment]
I specified webrick for capybara in test_helper.

**Comment by akiko-pusu** [comment]
Hi, @two-pack 
Thanks for your information and saving my life :)
I saw the same situation on my CI test env against Redmine 3.x.

It seems we have to specify application server’s name in case not using puma...
https://github.com/teamcapybara/capybara/commit/6f48859a607efcc4498e93d8026874af5afd4fb7
