### ISSUE TITLE
Feature Enhancements

### ISSUE THREAD

**Issue by Huangzc88** [two-pack/redmine_xlsx_format_issue_exporter#66]
It's a very easy plugin.
Give some advice:
1.Add Export attachments Feature
2.Related issues and sub-tasks or parent task columns also add hyperlinks

**Comment by two-pack** [comment]
Thank you for giving advices.

> 1.Add Export attachments Feature

This plugin's concept is export XLSX format issues list like CSV export.
So I don't want to implement the feature to export attachments.
But it may be possible to consider if linking is done.

> 2.Related issues and sub-tasks or parent task columns also add hyperlinks

it may be possible to consider it.

The above two functions are separate things.
Could you recreate it separately?

**Comment by Huangzc88** [comment]
Thank you very much for your reply. I'll rebuild 2 issue.

**Comment by two-pack** [comment]
> Thank you very much for your reply. I'll rebuild 2 issue.

Thanks for creating #68 and #69 !
