### ISSUE TITLE
Add Export attachments Feature

### ISSUE THREAD

**Issue by Huangzc88** [two-pack/redmine_xlsx_format_issue_exporter#68]
I think you can add a hyperlink to the Attachment column first, and then see if it's possible to export a compressed package file that contains attachments, thanks.

**Comment by two-pack** [comment]
I already commented following on #66.

> This plugin's concept is export XLSX format issues list like CSV export.
> So I don't want to implement the feature to export attachments.
> But it may be possible to consider if linking is done.
