### ISSUE TITLE
Access violation issue - able to export private notes

### ISSUE THREAD

**Issue by danaivehr** [two-pack/redmine_xlsx_format_issue_exporter#73]
If user have no access to view private notes, he still able to get the private not, if it is the last one, just through "with last note" export option.

Steps to reproduce:
* Create user w/o right to view private note
* Create private note in issue
* Logon as user w/o right to view private note
* Export issue list to xlsx with "include last note" checked

Result:
* xlsx file will contain a private note

Expected:
* last not private note should be in xlsx

I use version 0.1.5

**Comment by danaivehr** [comment]
Issue exsists in 0.1.6 too.

Important note: when "last note" is present in query and shows up in list, xlsx gets last non-private note inside. So issue reproduces only when last note is not in the query

**Comment by two-pack** [comment]
Thank you for reporting.
I fixed it.

**Comment by danaivehr** [comment]
I confirm it is fixed. Thanks!
