### ISSUE TITLE
Convert Html Entities on XLSX Export (CKEditor)

### ISSUE THREAD

**Issue by hoangmn3s** [two-pack/redmine_xlsx_format_issue_exporter#78]
After using CKEditor to save Data (Description/Notes) 
Data save with HTML Entities format and still keep it on export 
Ex: 
`line1<br>
<strong>line2</strong>`

**Comment by hoangmn3s** [comment]
I fixed on use : 
Nokogiri & CGI 

`
require 'nokogiri'
require 'cgi'

Nokogiri::HTML(CGI.unescapeHTML(**htmlCode**)).content`

Docs : https://roratmindfiresolutions.wordpress.com/2013/10/09/how-to-remove-html-characters-from-encoded-html-string-in-ruby/

**Comment by aozhi2nd** [comment]
Hi,how to fix it?  which file?

**Comment by two-pack** [comment]
> Hi,how to fix it?  which file?

This plugin is not tests and supported  with other plugins.
If you will fork and fix it, I think you should see xlsx_export_helper.rb first.
