### ISSUE TITLE
NoMethodError: undefined method `around_filter' for CalendarsController:Class

### ISSUE THREAD

**Issue by n0rvik** [two-pack/redmine_xlsx_format_issue_exporter#85]
Hi

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Mercurial                      5.2.2
  Bazaar                         2.5.1
  Git                            2.9.3
  Filesystem                     
  Xitolite                       2.9.3
Redmine plugins:
  additionals                    2.0.23
  progressive_projects_list      4.0.0
  redmine_git_hosting            4.0.1
  redmine_issue_badge            0.1.3
  redmine_tags                   4.0.0
  

Install plugins
bundle exec rake redmine:plugins:migrate NAME=redmine_xlsx_format_issue_exporter RAILS_ENV=production

Error:
rake aborted!
NoMethodError: undefined method `around_filter' for CalendarsController:Class
Did you mean?  around_action
/mnt/storage/opt/redmine/redmine/plugins/redmine_advanced_roadmap_v2/lib/advanced_roadmap/calendars_controller_patch.rb:8:in `block in included'

**Comment by two-pack** [comment]
Thank you for reporting it 🙂
Can you install this plugin without redmine_advanced_roadmap_v2?
And please show directories list in plugins directory, because redmine_advanced_roadmap_v2 is not in installed plugins list.

**Comment by n0rvik** [comment]
### I apologize. I made a mistake. Your plugin just got great.


```
[~/redmine/plugins]$ ll
total 12
drwxr-xr-x 11 redmine redmine 4096 Feb 28 11:43 additionals
drwxr-xr-x  7 redmine redmine  118 Feb 28 11:39 progressive_projects_list
-rw-r--r--  1 redmine redmine   31 Feb 28 11:39 README
drwxr-xr-x 10 redmine redmine  232 Feb 28 17:16 redhopper
drwxr-xr-x 11 redmine redmine  273 Feb 28 16:44 redmine_dashboard
drwxr-xr-x  9 redmine redmine  244 Feb 28 15:25 redmine_drawio
drwxr-xr-x 11 redmine redmine  306 Feb 28 11:57 redmine_git_hosting
drwxr-xr-x 13 redmine redmine 4096 Feb 28 12:36 redmine_issue_badge
drwxr-xr-x 10 redmine redmine  227 Feb 28 15:44 redmine_issue_evm
drwxr-xr-x  9 redmine redmine  129 Feb 28 13:22 redmine_issue_todo_lists
drwxr-xr-x  9 redmine redmine  261 Feb 28 11:39 redmine_tags
drwxr-xr-x  9 redmine redmine  281 Feb 28 18:34 redmine_theme_changer
drwxr-xr-x  8 redmine redmine  147 Mar  2 13:36 redmine_xlsx_format_issue_exporter

```
