### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by enricod** [two-pack/redmine_xlsx_format_issue_exporter#88]
We have a fresh 4.0.0 Redmine installation, on ubuntu

Environment:
  Redmine version                4.0.0.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  no plugin installed

Opening the projects page we get

Processing by ProjectsController#index as HTML
  Current user: EDO (id=9)
  Rendering projects/index.html.erb within layouts/base
  Rendered projects/index.html.erb within layouts/base (11.9ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_projects_index.erb (3.0ms)
Completed 500 Internal Server Error in 46ms (ActiveRecord: 7.4ms)
  
ActionView::Template::Error (undefined method `display_type' for nil:NilClass):
    1: <% if @query.display_type == 'list' %>
    2:   <%= render :partial => "hooks/insert_xlsx_link_for_dialog" %>
    3: 
    4:   <div id="xlsx-export-options" style="display:none;">
  
plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_projects_index.erb:1:in `_plugins_redmine_xlsx_format_issue_exporter_app_views_hooks__xlsx_export_dialog_on_projects_index_erb___4374844539903717429_70324759601740'
plugins/redmine_xlsx_format_issue_exporter/lib/redmine_xlsx_format_issue_exporter/view_layouts_base_body_bottom_hook.rb:20:in `view_layouts_base_body_bottom'
lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:61:in `each'
lib/redmine/hook.rb:61:in `block in call_hook'
lib/redmine/hook.rb:58:in `tap'
lib/redmine/hook.rb:58:in `call_hook'
lib/redmine/hook.rb:96:in `call_hook'
app/views/layouts/base.html.erb:124:in `_app_views_layouts_base_html_erb___4004329369597435921_47193101792700'

**Comment by two-pack** [comment]
Thank you for reporting it :)
I'll check it.

**Comment by two-pack** [comment]
I could reproduce this problem.
I fix it and create PR #89 :)
Thank you for reporting :)

**Comment by marcellohi** [comment]
I just installed it in the environment detailed in first comment and I confirm that everything works perfectly. Thank you! :)
