### ISSUE TITLE
its not working in redmineup plugins

### ISSUE THREAD

**Issue by ashrafalzyoud** [two-pack/redmine_xlsx_format_issue_exporter#92]
can u do ant things to use your plugin with redmineup plugins
contacts product invoice finiance plugins

**Comment by two-pack** [comment]
Thank you for reporting.
What's happen when you use this plugin with them? Errors? not exporting? or something else?

I try to check it and success to export issues list.
Can you write more details of your installation, environment, and what's happend? See: [How to report issue](https://github.com/two-pack/redmine_xlsx_format_issue_exporter/wiki/How-to-report-issue)

NOTE: I check followings:
* My environment. redmine_xlsx_format_issue_exporter was cloned master.
~~~
Environment:
  Redmine version                4.2.2.stable.21188
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  5.2.6
  Environment                    development
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  redmine_contacts               4.3.4
  redmine_contacts_invoices      4.2.5
  redmine_xlsx_format_issue_exporter 0.1.6
~~~
*  I use **Light edition** of **REDMINE INVOICES PLUGIN** and **REDMINE CRM PLUGIN** .

**Comment by ashrafalzyoud** [comment]
I'm use redmine 4.2.2
Last version RedmineUP plugins pro
The problem it's
The icon xlsx not appear just only CSV in invoice and product

**Comment by two-pack** [comment]
> The icon xlsx not appear just only CSV in invoice and product

This plugin supports only original functions of Redmine, Issues, Spent time, and Users.
So it cannot export with functions of other plugins like REDMINE INVOICES PLUGIN.

**Comment by ashrafalzyoud** [comment]
If u can help because your plugin very important

**Comment by two-pack** [comment]
> If u can help because your plugin very important

Thank you for using this plugin :)
Of course, you can also customize this plugin **YOURSELF** to use it.
But I do not think it is appropriate to discuss individual customizations here.
If it is difficult for you to customize yourself, you may be able to find a developer [here](https://www.redmine.org/projects/redmine/boards/5) or contact from my profile.
