### ISSUE TITLE
redmine 5.0

### ISSUE THREAD

**Issue by ashrafalzyoud** [two-pack/redmine_xlsx_format_issue_exporter#95]
can u update to redmine 5.0?

**Comment by two-pack** [comment]
Basically, No. I will consider it if we gather many opinions of continued support.

**Comment by ashrafalzyoud** [comment]
This feature is considered one of the strongest and most beautiful and one of the most important foundations, and we always need permanent support. We hope that you will always update

**Comment by marmat1** [comment]
Exporting .xlsx is already as a redmine core functionality for us. It would be very helpful to keep this plugin updated.

**Comment by two-pack** [comment]
NOTE: #96 , #94

**Comment by two-pack** [comment]
I release v0.1.7 which supports Redmine 5.0.0. Thanks all for comments and contribution #96  :)
https://github.com/two-pack/redmine_xlsx_format_issue_exporter/releases/tag/0.1.7
