### ISSUE TITLE
Custom field with full layout setting not exported 

### ISSUE THREAD

**Issue by boki69** [two-pack/redmine_xlsx_format_issue_exporter#98]
Hi two-pack!

First of all, I have to thank you for this great plugin!

I think, I found a bug with Redmine 5.

Test scenario for reproduce the wrong behaviour:

1.  Create a custom field like in this picture with **Full Width layout** setting:
![kép](https://user-images.githubusercontent.com/3695756/196440898-94bb0e55-57fd-477c-9466-83ec38520378.png)
2. Create an issue with this custom field:
![kép](https://user-images.githubusercontent.com/3695756/196441288-4aba341e-25eb-4b8a-9213-bc5b8dcb5d09.png)
3. Filter issues like on the picture (If you check to show this column, it appears under the issue. Cannot select in Available Columns):
![kép](https://user-images.githubusercontent.com/3695756/196442869-56a11762-6296-4f18-b7d1-7bfdffa54ab6.png)
4. Cannot set to export in modal window and it is not exported to downloaded xls.
![kép](https://user-images.githubusercontent.com/3695756/196443576-030d6af5-f75b-4cb4-8b08-324e60c8bc94.png)
![kép](https://user-images.githubusercontent.com/3695756/196443622-1c42e04a-9d38-4ec4-b9db-0882c262a9d9.png)

I make a modification in **app/views/hooks/_xlsx_export_dialog_on_issues_index.erb** after line 20, and it works for me:

`        <% @query.available_columns.each do |c|
            if !c.inline? and !['last_notes','description'].include?(c.name.to_s) %>
              <label><%= check_box_tag "#{c.name.to_s}", '1', @query.has_column?(c.name) %> <%= c.custom_field.name %></label><br />
            <% end %>
        <% end %>
`
And the end of line 17 and 19 insert this code:

`<br />`

Test results:

1. Modal window:
![kép](https://user-images.githubusercontent.com/3695756/196445050-e7318122-bfb4-40fe-b338-fb234f6243a5.png)

2. It is the last column in exported xls:
![kép](https://user-images.githubusercontent.com/3695756/196445260-62ab6fbd-1685-499b-8511-6fe20536a70e.png)

Best regards!

**Comment by two-pack** [comment]
Thank you for reporting the issue.
I think this problem is like following csv exporting bug of Redmine.
https://www.redmine.org/issues/33169

So how to fix it is like that too.
I am going to check and fix it, but I need time to do that.

**Comment by two-pack** [comment]
We have begun to correct this problem.
I am trying to fix it to work with Redmine 4.2.x or later, as the process for older versions is getting in the way and making it difficult to fix.
This is going to take long time as it is going to require a major fix.

**Comment by boki69** [comment]
@two-pack ,

I've tested these scenarios (issue and timelog parts of Redmine):
1. Export only selected columns and the fulll layout custom field. 
2. Export all columns with the fulll layout custom field. 
3. Export datas when the fulll layout custom field was checked before I start export dialog

Everything is fine. Good job, thank you!

**Comment by two-pack** [comment]
Thanks @boki69 ‼️
I'll merge this fix after more tests.

**Comment by two-pack** [comment]
I'm testing it, and got two bugs,
* Fail to export user list.
* Some unessesary headers on timelog export.

I continue to fix them and test it.

**Comment by two-pack** [comment]
I fixed this problem and merged.
Thanks @boki69 for reporting it☺
